### ISSUE TITLE
0.59.3  TextInput component on Android getting other side on textAlign

### ISSUE THREAD

**Issue by tamirrab** [react-native-community/react-native-releases#111]
Hi
TextInput:
on Android only, textAlign: "right" doing "left" instead of right.
and "left" doing "right" instead of left.

And the the textAlign property doesn't effect the placeholder at all

only on 0.59.3 and only on Android

**Comment by FibreFoX** [comment]
@tamirrab please close this, as this has nothing to do with this repository.
