### ISSUE TITLE
[Question] Can we safely use React 16.8.4 or higher with RN 0.59.4?

### ISSUE THREAD

**Issue by lorenc-tomasz** [react-native-community/react-native-releases#115]
Hi,
we had long discussion within the team about it but without consensus. Maybe you can help?

**Comment by Bardiamist** [comment]
@lorenc-tomasz You can't safely use another version because it required sync commit from Facebook. Example for React 16.8.3: https://github.com/facebook/react-native/commit/d4ce8463a853a29cc977fcbf390b43940f521bd2 . This have many changes besides raising version.

**Comment by lorenc-tomasz** [comment]
Thanks. Sadly I was right as new react-redux requires at least 16.8.4

**Comment by Bardiamist** [comment]
@lorenc-tomasz I think you can use new react-redux. `react-redux` should download and use required dependencies (`react` 16.8.4) but `react native` will still use react from you'r `package.json`.

**Comment by jkdf2** [comment]
@lorenc-tomasz See: https://github.com/reduxjs/react-redux/pull/1242

react-redux will work with 16.8.3.
