### ISSUE TITLE
Setting child height to 100% does not work when parent has paddingVertical

### ISSUE THREAD

**Issue by apcjs** [react-native-community/react-native-releases#17]
This is my render code:

```
    return (<View style={{
      display: "flex",
      backgroundColor: "green",
      paddingVertical: 20
    }}>
      <View style={{ backgroundColor: "red", flex: 1, position: "absolute", height: "100%", width: "100%" }} />
      <Text>This is the text</Text>
      <Text>This is the text</Text>
      <Text>This is the text</Text>
      <Text>This is the text</Text>
    </View>)

```
What is see is the following:
![capture](https://user-images.githubusercontent.com/328103/39182452-9abf0116-47da-11e8-8e08-442256cf4ea6.JPG)

What I expected was the height of the red child View to match the height of the parent green View.

**Comment by donni106** [comment]
Maybe you can achieve what you want if you add the outer padding as margin `marginVertical: 20` to the red one?

**Comment by anp** [comment]
This looks like an issue for the main react-native repo?

**Comment by turnrye** [comment]
Hi @apcjs, please log this in facebook/react-native.
