### ISSUE TITLE
Should I edit 0.56 changelog ?

### ISSUE THREAD

**Issue by Titozzz** [react-native-community/react-native-releases#20]
Hello,

One of my fixes is going to land in 0.56 🎉 and it might impact previous usage / workarounds with the local-cli link command:
https://github.com/facebook/react-native/commit/dbd47592a18ed09ee6e94c79bed16d63be625af6

Do you guys need me to add this to the changelog, or is it not necessary ?

Thanks for the hard work on 0.56 ⚡️

**Comment by hramos** [comment]
Please do!
