### ISSUE TITLE
cherry-pick requests for Gboard emoji crash commit for RN 0.55

### ISSUE THREAD

**Issue by malonguwa** [react-native-community/react-native-releases#27]
@hramos or anybody, Could you mind to cherry pick commit (https://github.com/facebook/react-native/commit/41975f75d96ef4b606b4618461bf24d5db063b77) into the RN0.55 release?

I understand 0.56 included this commit, but in my case, we are very close to release our RN app, and we have tested 0.55 for weeks, so far the only issue left is this android emoji crush in suggestion bar, and this commit solved it, I would really hope you can consider my request, 0.56 introduced new versions requirements, and 0.56 may also introduce more new bugs, but we do not have enough time upgrade RN and test at this moment, we will definitely upgrade our RN later, but at the moment, I am really hope if you guys can consider to cherry pick this commit to RN 0.55. 

Much appreciated !!!

**Comment by grabbou** [comment]
Thank you for filling in this support request. Just a reminder to anyone who is reading this issue - please post backport requests inside corresponding issues. 

Moving to here: https://github.com/react-native-community/react-native-releases/issues/11#issuecomment-400367052
