### ISSUE TITLE
0.57.x (latest: 0.57.0-rc.3)

### ISSUE THREAD

**Issue by grabbou** [react-native-community/react-native-releases#33]
Latest: https://www.npmjs.com/package/react-native/v/0.57.0-rc.0

**Comment by danielgindi** [comment]
Any news on this guys? 23rd has come and gone :-)

**Comment by grabbou** [comment]
Unfortunately, the release has been delayed due to issues with running and building React Native on Windows. We are currently investigating the state of `master` and trying to get it into the deployable state as soon as possible.

The team at Facebook is busy this week with internal work and so, it takes a bit more than usual.

**Comment by grabbou** [comment]
New release is out: https://www.npmjs.com/package/react-native/v/0.57.0-rc.0

**Comment by grabbou** [comment]
New release is out: https://www.npmjs.com/package/react-native/v/0.57.0-rc.3
