### ISSUE TITLE
[0.54] Improve one changelog information

### ISSUE THREAD

**Issue by brunolemos** [react-native-community/react-native-releases#4]
The changelog has the following text:

> Revive react-native-xcode.sh made improvements ([b8c86b8](https://github.com/facebook/react-native/commit/b8c86b8) and [0d4ff1b](https://github.com/facebook/react-native/commit/0d4ff1b) by @yungsters and @brunolemos)

, pointing to two "remove all" / "re-add file" commits due to facebook-bot bug.

That's not clear to the user what has changed (and even kinda makes it look like I messed up).

The text could be something like this:
> `[iOS] Add $EXTRA_PACKAGER_ARGS extensibility point on react-native-xcode.sh script` (https://github.com/facebook/react-native/pull/16933) by @brunolemos

**Comment by turnrye** [comment]
@brunolemos thanks for the feedback! Good callout – I missed that the "revive" commit was to address an accidental deletion. It doesn't belong in the changelog, which then makes your change and PR more succinct.

**Comment by brunolemos** [comment]
Yeah... I see you always point to the specific merged commits, but in this specific case that would be confusing.

**Comment by turnrye** [comment]
Right -- that is the practice. I'll add a note this time that the landing was a bit bumpy 😂

**Comment by brunolemos** [comment]
@turnrye thanks! Made #5 too, as it is an addition targeting end users, not internal work.

How could we get these changes on https://github.com/facebook/react-native/releases? 
That's where people really look.

**Comment by turnrye** [comment]
I'll ping the core team and they'll get it revised; will probably take about 12-24 hrs.

**Comment by brunolemos** [comment]
Thanks @turnrye I'll check it out tomorrow

**Comment by brunolemos** [comment]
They updated 💯💯
