### ISSUE TITLE
Suggestion: Include jest upgrade path to changelog

### ISSUE THREAD

**Issue by ferdicus** [react-native-community/react-native-releases#56]
Hey there, sorry, not sure if this is the place for this.
However, after having some major pains trying to upgrade jest to play nice with tests for RN 0.57.3

I wondered if there should be a upgrade path described within the changelog for the defacto testing framework of RN as well.

Thanks

**Comment by kelset** [comment]
I'm not entirely sure what you mean with "upgrade path", but feel free to submit a PR and we'll review it 😃

**Comment by ferdicus** [comment]
Sorry, I should've been more precise with the initial comment.

I've seen long issue threads in the react-native repo about people having issues with setting up/ debugging jest issues after upgrading to rn `0.57.x`. 

I think it would be useful to include the testing configuration in the changelog as well.

I would love to add a PR with a working setup - however I wasn't able to fix my issues so far.
Either the snapshots seem to render but my mocks fail or the other way around....

Anyways, as the prefix says it's more of a suggesting/ request.

Thanks

**Comment by TheSavior** [comment]
@ferdicus can you open an issue on the main repo with repro steps? We definitely want Jest to be working. Ideally if you can start from a blank project and provide a test that used to work on a previous version but no longer works on the latest version then we should be able to resolve this.
