### ISSUE TITLE
No info about upgrading gradle version

### ISSUE THREAD

**Issue by DaniAkash** [react-native-community/react-native-releases#59]
Hi, 

I upgraded my react native project from 0.56 to 0.57 using the steps provided in [this repository](https://github.com/react-native-community/react-native-releases/blob/master/CHANGELOG.md#updating-to-this-version) because I was facing facebook/react-native#18886 issue. 

However after upgrading my project, the static images are not properly bundled together in my react native project which is referenced at facebook/react-native#21309 issue. Later I wanted to use firebase in my project hence had to install react-native-firebase. There, I followed their instructions to [upgrade my project to Gradle 4.4 ](https://rnfirebase.io/docs/v5.x.x/installation/android#Update-Gradle). After the upgrade, the static images got bundled properly.

I think the steps to upgrade gradle is a necessary info to provide in the changelog in this repository which will fix issue with bundling static images in android....

**Comment by kelset** [comment]
Thanks for the feedback, can you submit a PR to improve the Changelog? It surely would help also others :)

**Comment by DaniAkash** [comment]
@kelset sure! will submit a PR soon...

**Comment by kelset** [comment]
(closing since there is a PR now)
