### ISSUE TITLE
0.54 - Fix Live Reload regression

### ISSUE THREAD

**Issue by hramos** [react-native-community/react-native-releases#7]
A fix for https://github.com/facebook/react-native/issues/18209 is now on master, but is not yet part of any release.

This fixes a regression that is preventing live reloading from working correctly in 0.54 and 0.55.

Would we consider releasing a 0.54.2 version with this fix?

As for 0.55, the fix should make it when the RC is cut.

**Comment by grabbou** [comment]
Yes, thank you @hramos for opening up this issue - it is way more cleaner to handle releases in this repo as opposed to having it all over in `react-native` repository. Picking this up.
