### ISSUE TITLE
Size is bigger than older version 

### ISSUE THREAD

**Issue by jagadishg1** [react-native-community/react-native-releases#91]
When compared to other versions Size is increased which is a key point , So is there any way to reduce size in react native 0.58.4 , Just for one page it took 18MB
The following are my dependencies
`    "react": "16.6.3",
    "react-native": "0.58.4",
    "react-native-elements": "^1.0.0",
    "react-native-gesture-handler": "^1.0.15",
    "react-native-vector-icons": "^6.3.0",
    "react-navigation": "^3.2.3"`

**Comment by diegolmello** [comment]
@jagadishg1 While your comment is valid, you should be comparing only a "Hello world" vanilla RN 0.57.8, against 0.58.4, for example.
Other libs could interfere.

That said, there's a huge Lean Core effort [here](https://github.com/facebook/react-native/issues/23313), but it only adds deprecation warnings for now and it'll fully remove some dependencies on 0.61 (maybe?).

Finally, I think this is not the best place for this discussion.
Probably, in the Lean Core issue it would be better.

**Comment by mjmasn** [comment]
@jagadishg1 As far as I know it's because https://github.com/facebook/react-native/commit/0a2825f8b3dc183bb17c9aa18d778ddb0f641a66 and https://github.com/facebook/react-native/commit/f3e5cce4745c0ad9a5c697be772757a03e15edc5 added `arm64-v8a` and `x86-64` build types, so the base APK size has probably just about doubled.

You can do APK splitting per build type for smaller APKs if necessary. If you're distributing on the Play Store then you just upload multiple APKs for a release and Google will deliver the right APK for the end user's device.

**Comment by mikehardy** [comment]
@mjmasn exactly that, you can also package using the new android buncdle style and goigle will even take care of only sending image assets with the correct dpi along with just the correct binary architecture, making the end user downloads even smaller if that is a concern

**Comment by hramos** [comment]
As @diegolmello said earlier in the thread, this is not the right place to discuss this. We use this repository to coordinate open source releases, and this falls out of that scope.

**Comment by SaeedZhiany** [comment]
@hramos, So I think it would be better transfer this issue to a right place than close it. I have the issue too. My apk size increased double and I don't know how exactly manage that. also I don't have any information about the 'splitting' procedure that @mjmasn said.

**Comment by jagadishg1** [comment]
> @jagadishg1 While your comment is valid, you should be comparing only a "Hello world" vanilla RN 0.57.8, against 0.58.4, for example.
> Other libs could interfere.
> 
> That said, there's a huge Lean Core effort [here](https://github.com/facebook/react-native/issues/23313), but it only adds deprecation warnings for now and it'll fully remove some dependencies on 0.61 (maybe?).
> 
> Finally, I think this is not the best place for this discussion.
> Probably, in the Lean Core issue it would be better.

Thanks for your quick response , ill create another issue in Lean core

**Comment by jagadishg1** [comment]
> @mjmasn exactly that, you can also package using the new android buncdle style and goigle will even take care of only sending image assets with the correct dpi along with just the correct binary architecture, making the end user downloads even smaller if that is a concern

Thanks for your response , do you have any reference link for making app bundle for react native app

**Comment by mikehardy** [comment]
> Thanks for your response , do you have any reference link for making app bundle for react native app

https://developer.android.com/platform/technology/app-bundle/

**Comment by hramos** [comment]
@SaeedZhiany issues can only be transferred across repositories in the same GitHub org, and the core RN repo is not part of @react-native-community. Other repositories have issue templates that might need to be applied. It's best to let the OP handle submitting the issue elsewhere.

**Comment by diegolmello** [comment]
> @hramos, So I think it would be better transfer this issue to a right place than close it. I have the issue too. My apk size increased double and I don't know how exactly manage that. also I don't have any information about the 'splitting' procedure that @mjmasn said.

https://facebook.github.io/react-native/docs/signed-apk-android#split-apks-by-abi-to-reduce-file-size

**Comment by SimenB** [comment]
>issues can only be transferred across repositories in the same GitHub org

Not really, but you have to be an admin on both repos (push access not enough). Unfortunate restriction, IMO.

Good point on the issue templates, though 🙂
